# Generated by Django 2.2.17 on 2021-02-02 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.CharField(max_length=32)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '区域',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
                ('place', models.CharField(max_length=32)),
                ('map', models.CharField(max_length=32)),
                ('zoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Zone')),
            ],
            options={
                'verbose_name_plural': '位置',
            },
        ),
    ]
