# Generated by Django 2.2.17 on 2021-01-14 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('region', '0002_department_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.CharField(max_length=32)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '区域',
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='zoon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Zone'),
        ),
        migrations.DeleteModel(
            name='Zoon',
        ),
    ]
