# Generated by Django 2.2.17 on 2021-01-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0004_auto_20210114_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
